name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup CassiaExt
      run: |
        git clone https://github.com/cassia-org/cassiaext
        python3 cassiaext/deps/apply-patches.py 
        printf "$(pwd)/cassiaext\n\
        cmake -GNinja -Bbuild -H. \
        -DCMAKE_TOOLCHAIN_FILE=\${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-29 \
        -DANDROID_SDK=\${ANDROID_SDK_HOME} -DANDROID_NDK=\${ANDROID_NDK_HOME} \
        -DANDROID_ABIS=arm64-v8a" \
        > app/cassiaext.cfg
        cat app/cassiaext.cfg
        
    - name: Build with Gradle
      run: | 
         chmod +x gradlew
         ./gradlew assembleDebug

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
