name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
           ninja-build \
           meson \
           build-essential \
           cmake \
           jq

    - name: Download Android NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '25.2.9519653'

    - name: Setup CassiaExt
      run: |
        git clone https://github.com/Ishan09811/cassiaext/
        cd cassiaext
        export ANDROID_NDK_HOME=${ANDROID_NDK_HOME}
        export ANDROID_SDK_HOME=${ANDROID_SDK_HOME}
        export PATH=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH

        # Logging environment variables for debugging
        echo "ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
        echo "ANDROID_SDK_HOME=${ANDROID_SDK_HOME}"
        echo "PATH=${PATH}"

        # Ensure submodules are updated
        git submodule update --init --recursive
        # Apply patches
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        python3 deps/reset-deps.py
        python3 deps/apply-patches.py

        # CMake build command with debugging
        export CI=true
        cmake -GNinja -Bbuild -H. \
          -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-29 \
          -DANDROID_SDK=${ANDROID_SDK_HOME} \
          -DANDROID_NDK=${ANDROID_NDK_HOME} \
          -DANDROID_ABIS=arm64-v8a

        # Log generated CMake files for debugging
        find build -name "libandroidshmem-build-*.cmake" -exec cat {} \;
        
        cmake --build build --verbose
      continue-on-error: true

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
      continue-on-error: true

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          ./cassiaext/build/libxtrans-prefix/src/libxtrans-stamp/libxtrans-generate-*.log
          ./cassiaext/build/xorgproto-prefix/src/xorgproto-stamp/xorgproto-generate-*.log

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
